export const tokens = {
  color: {
    primary: '#FF5000',
    primaryLight: '#FF7A33',
    primaryDark: '#E64800',
    primaryBg: '#FFF5F0',
    price: '#FF0000',
    priceDark: '#E8380D',
    sale: '#FF3B30',
    success: '#07C160',
    successLight: '#E8F8EF',
    warning: '#FFA726',
    warningLight: '#FFF8E6',
    error: '#FF3B30',
    info: '#1890FF',
    textPrimary: '#1A1A1A',
    textSecondary: '#666666',
    textTertiary: '#999999',
    textPlaceholder: '#CCCCCC',
    textWhite: '#FFFFFF',
    bgPage: '#F5F5F5',
    bgWhite: '#FFFFFF',
    bgCard: '#FFFFFF',
    border: '#EEEEEE',
    divider: '#F0F0F0',
  },
  spacing: {
    xxs: '2px',
    xs: '4px',
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '20px',
    xxl: '24px',
    xxxl: '32px',
  },
  radius: {
    xs: '4px',
    sm: '6px',
    md: '8px',
    lg: '12px',
    xl: '16px',
    xxl: '24px',
    round: '9999px',
  },
  fontSize: {
    xs: '10px',
    sm: '12px',
    md: '14px',
    lg: '16px',
    xl: '18px',
    xxl: '20px',
    xxxl: '24px',
  },
} as const;
